{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "pagepal.fullname" . }}
  labels:
    {{- include "pagepal.labels" . | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/use-regex: "true"
    {{- if .Values.ingress.clusterIssuer }}
    cert-manager.io/cluster-issuer: {{ .Values.ingress.clusterIssuer | quote }}
    {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className | quote }}
  {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
    - hosts:
        - {{ required "ingress.host is required when ingress is enabled" .Values.ingress.host }}
      secretName: {{ .Values.ingress.tlsSecretName }}
  {{- end }}
  rules:
    - host: {{ required "ingress.host is required when ingress is enabled" .Values.ingress.host }}
      http:
        paths:
          - path: /api/?(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ include "pagepal.fullname" . }}-api
                port:
                  name: http
          - path: /(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ include "pagepal.fullname" . }}-web
                port:
                  name: http
{{- end }}
