{{- if not .Values.postgresql.auth.existingSecret }}
{{- if not (lookup "v1" "Secret" .Release.Namespace (include "pagepal.dbSecretName" .)) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pagepal.dbSecretName" . }}
  labels:
    {{- include "pagepal.labels" . | nindent 4 }}
  annotations:
    "helm.sh/resource-policy": "keep"
type: Opaque
stringData:
  password: {{ randAlphaNum 32 }}
{{- end }}
{{- end }}
