/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as WidgetPreviewRouteImport } from './routes/widget-preview'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardAccountRouteImport } from './routes/dashboard/account'
import { Route as DashboardAnalyticsRouteImport } from './routes/dashboard/analytics'
import { Route as DashboardBotsRouteImport } from './routes/dashboard/bots'
import { Route as DashboardWidgetRouteImport } from './routes/dashboard/widget'
import { Route as DashboardBotBotIdRouteImport } from './routes/dashboard/bot.$botId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const WidgetPreviewRoute = WidgetPreviewRouteImport.update({
  id: '/widget-preview',
  path: '/widget-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardAccountRoute = DashboardAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardAnalyticsRoute = DashboardAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardBotsRoute = DashboardBotsRouteImport.update({
  id: '/bots',
  path: '/bots',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardWidgetRoute = DashboardWidgetRouteImport.update({
  id: '/widget',
  path: '/widget',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardBotBotIdRoute = DashboardBotBotIdRouteImport.update({
  id: '/bot/$botId',
  path: '/bot/$botId',
  getParentRoute: () => DashboardRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/widget-preview': typeof WidgetPreviewRoute
  '/dashboard/account': typeof DashboardAccountRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/bots': typeof DashboardBotsRoute
  '/dashboard/widget': typeof DashboardWidgetRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/bot/$botId': typeof DashboardBotBotIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/widget-preview': typeof WidgetPreviewRoute
  '/dashboard/account': typeof DashboardAccountRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/bots': typeof DashboardBotsRoute
  '/dashboard/widget': typeof DashboardWidgetRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/bot/$botId': typeof DashboardBotBotIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/widget-preview': typeof WidgetPreviewRoute
  '/dashboard/account': typeof DashboardAccountRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/bots': typeof DashboardBotsRoute
  '/dashboard/widget': typeof DashboardWidgetRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/bot/$botId': typeof DashboardBotBotIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/widget-preview'
    | '/dashboard/account'
    | '/dashboard/analytics'
    | '/dashboard/bots'
    | '/dashboard/widget'
    | '/dashboard/'
    | '/dashboard/bot/$botId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/widget-preview'
    | '/dashboard/account'
    | '/dashboard/analytics'
    | '/dashboard/bots'
    | '/dashboard/widget'
    | '/dashboard'
    | '/dashboard/bot/$botId'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/widget-preview'
    | '/dashboard/account'
    | '/dashboard/analytics'
    | '/dashboard/bots'
    | '/dashboard/widget'
    | '/dashboard/'
    | '/dashboard/bot/$botId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  WidgetPreviewRoute: typeof WidgetPreviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/widget-preview': {
      id: '/widget-preview'
      path: '/widget-preview'
      fullPath: '/widget-preview'
      preLoaderRoute: typeof WidgetPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/account': {
      id: '/dashboard/account'
      path: '/account'
      fullPath: '/dashboard/account'
      preLoaderRoute: typeof DashboardAccountRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/analytics': {
      id: '/dashboard/analytics'
      path: '/analytics'
      fullPath: '/dashboard/analytics'
      preLoaderRoute: typeof DashboardAnalyticsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/bots': {
      id: '/dashboard/bots'
      path: '/bots'
      fullPath: '/dashboard/bots'
      preLoaderRoute: typeof DashboardBotsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/widget': {
      id: '/dashboard/widget'
      path: '/widget'
      fullPath: '/dashboard/widget'
      preLoaderRoute: typeof DashboardWidgetRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/bot/$botId': {
      id: '/dashboard/bot/$botId'
      path: '/bot/$botId'
      fullPath: '/dashboard/bot/$botId'
      preLoaderRoute: typeof DashboardBotBotIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
  }
}

interface DashboardRouteRouteChildren {
  DashboardAccountRoute: typeof DashboardAccountRoute
  DashboardAnalyticsRoute: typeof DashboardAnalyticsRoute
  DashboardBotsRoute: typeof DashboardBotsRoute
  DashboardWidgetRoute: typeof DashboardWidgetRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardBotBotIdRoute: typeof DashboardBotBotIdRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardAccountRoute: DashboardAccountRoute,
  DashboardAnalyticsRoute: DashboardAnalyticsRoute,
  DashboardBotsRoute: DashboardBotsRoute,
  DashboardWidgetRoute: DashboardWidgetRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardBotBotIdRoute: DashboardBotBotIdRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  WidgetPreviewRoute: WidgetPreviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
