apiVersion: v1
kind: Namespace
metadata:
  name: ${NAMESPACE}
  labels:
    cattle.io/creator: norman
  annotations:
    field.cattle.io/projectId: ${RANCHER_PROJECT_ID}
    field.cattle.io/resourceQuota: '{"limit":{"requestsCpu":"1500m","requestsMemory":"2048Mi","limitsCpu":"4000m","limitsMemory":"4096Mi"}}'
    field.cattle.io/containerDefaultResourceLimit: '{"requestsCpu":"100m","requestsMemory":"128Mi","limitsCpu":"500m","limitsMemory":"512Mi"}'
